### ISSUE TITLE
composer support

### ISSUE THREAD

**Issue by indeyets** [BraveSirRobin/amqphp#10]
Would be nice to have support for [Composer](http://getcomposer.org/doc/02-libraries.md)/[Packagist](http://packagist.org/). Installation and updates would become much easier

**Comment by tondacrha** [comment]
@BraveSirRobin I can create a Composer package for this repo. Apparently amqphp is the only lib out there supporting publisher acknowledgements using plain PHP.

**Comment by BraveSirRobin** [comment]
I'll look at this in the next couple of days - Composer is a new one for me!  BTW - AMQPHP uses code generation, what's the preferred way of dealing with this with composer?  I could either put pre-generated code in the composer package or generate on the fly (assuming composer supports this?)

If only composer didn't force you to write your configuration using JSON - euch!

**Comment by tondacrha** [comment]
Hi Robin,

in case you need build step during composer package installation, you can fire up pre-install or post-install event once composer package is downloaded.
Have a look at this basics: 
http://phpmaster.com/build-automation-with-composer-scripts/
http://getcomposer.org/doc/articles/scripts.md

**Comment by BraveSirRobin** [comment]
OK, I've created a package on Packagist:

https://packagist.org/packages/brave-sir-robin/amqphp

I haven't had time to test this and I've not used composer before, so if it's broken or wrong please let me know.  Pull requests are welcome :-)

**Comment by tondacrha** [comment]
I have created a pull request to correct the composer config file: https://github.com/BraveSirRobin/amqphp/pull/12

**Comment by BraveSirRobin** [comment]
Thanks Rotac - I've merged that now.  Let me know if this sorts the problem.

**Comment by tondacrha** [comment]
@BraveSirRobin I had been struggling with you repo for quite a while before I found possible problem.
In short: composer is asking for git password during the package installation - which is unusual.

The problem probably lies in the packagist (https://packagist.org/packages/brave-sir-robin/amqphp) package configuration.

Compare this:
source   : [git] git://github.com/rotac/amqphp.git   (working)
source   : [git] git@github.com:BraveSirRobin/amqphp.git   (not working)

Can you please update the packagist configuration to use the git:// schema in source attribute; and remove the "git@" user? The git user is probably the reason why I'm asked for git password. This has to be done somewhere on packagist.org page - I guess. 

And can you maybe remove the character "*" from the versions attribute?

Thanks a lot

**Comment by BraveSirRobin** [comment]
Hi Rotac,

I've set the source URL to this : git://github.com/BraveSirRobin/amqphp.git

Please try again and let me know how that goes.

Thanks,
--Robin

**Comment by tondacrha** [comment]
Hi Robin,
the package is now working fine. I just haven't yet had time to check the composer autoloader function...

Thanks for the change
