### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by laoneo** [BraveSirRobin/amqphp#11]
Hello
Does your library support SSL connections?

**Comment by BraveSirRobin** [comment]
Hi,

Yes, it does.  There's an SSL setup guide here:

https://github.com/BraveSirRobin/amqphp/wiki/SSL-Setup

You have to pass additional parameters to the Connection constructor, if you follow the nesting structure here (in comments on line 38):

https://github.com/BraveSirRobin/amqphp/blob/master/tests.old/forker.xml

..and convert the XML to an array it should work.  You'll also need to set up your broker to accept SSL connections.

HTH,
--Robin
