### ISSUE TITLE
ha-policy and ha-params not supported as queue.declare fields

### ISSUE THREAD

**Issue by ehberg** [BraveSirRobin/amqphp#13]
The policy params used by new versions of rabbit throw warnings when included as such:

(code has been abbreviated)

``` php
$params = array('ha-policy' => 'all');
$method = $this->defaultChannel->queue('declare', $params);
$this->connection->invoke($method);
```

That throws a warning, but DOES work when sent to Rabbit. Adding the policy in the attributes gets set in the queue parameter list, not policy. ie:

``` php
$params = array('arguments' => array('ha-policy' => 'all'));
$method = $this->defaultChannel->queue('declare', $params);
$this->connection->invoke($method);
```

This does not throw a warning, but DOES NOT work for setting policy. It's very possible im doing something wrong to properly send the policy information to Rabbit, what is the proper way?

**Comment by BraveSirRobin** [comment]
I suspect the Amqphp xml spec document is out of date - if you update this in the "tools" dir and run the phing build script this should bring in those fields defs.

BTW - I'm pretty sure the HA stuff won't work with Amqphp at the moment, I had a quick look at this a while back and the technical documentation from the RabbitMQ people was very scant.  Is this what you're trying to do?

**Comment by ehberg** [comment]
After looking into this more, Rabbit has changed their policy on policies. Here they describe the policy idea:

http://www.rabbitmq.com/parameters.html#policies

And in the changelog to version 3.0.0 they mention:
"allow queue mirroring to be defined by broker-wide policy, not queue declaration"
