### ISSUE TITLE
Full support for basic commands in amqp 0.9.1

### ISSUE THREAD

**Issue by aaronstaves** [BraveSirRobin/amqphp#2]
Just started using the library, so just let me know if I'm out of line :).  I'm using rabbitmq 2.4.1 on Ubuntu server 10.04.

It looks like you can just send basic commands using $ch->invoke, but it looks like there isn't support for _all_ 0.9.1 basic commands (as documented here - http://www.rabbitmq.com/amqp-0-9-1-quickref.html); purge and delete being 2 examples.

Is there support for these commands or am I just missing something ?  If not, any timeline as to when they might get implemented ?

**Comment by aaronstaves** [comment]
Looks like this isn't a basic command but a queue command!  

$purgeParams = array(
  'queue' => 'amqphp'
);
$purgeCommand = $ch->queue('delete', $purgeParams);
$resp = $ch->invoke($purgeCommand);

Sorry for clogging up the issues tab :-|

**Comment by BraveSirRobin** [comment]
Hi Aaron,

The basic procedure for calling Amqp methods is a 2 step process, as outlined in the docs in the section "AMQP 0.9.1 and the Amqphp API" (i.e. here: https://github.com/BraveSirRobin/amqphp/wiki/Documentation):

```
$msg = $chan->$amqpClass($amqpMethod, array('p1' => 'p1 value'), "method payload");
$resp = $chan->invoke($msg);
```

With reference to the Amqp guide on the RabbitMQ site, $amqpClass is one of 'basic', 'channel', 'confirm', etc.. and $amqpMethod is one of the methods listed in that class.  In the first line of code above you're not actually sending anything over the network, this happens in the second line.

Amqphp should have full support for all Amqp and Rabbitmq Amqp extensions, but this depends on which XML file you use to generate the bindings.  As time goes by the RabbitMQ people are adding more and more new Amqp commands, so if you ever find you're missing one of these you probably need to update your bindings by downloading the latest XML file and re-running the generation script.

HTH,
--Robin
