### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by hexuallyactive** [BraveSirRobin/amqphp#4]
How can one make a long-running consumer on Windows, since it does not support the pcntl functions?

**Comment by BraveSirRobin** [comment]
You don't have to use the pcntl functions, if you pass `'signalDispatch' => false` in the `Connection` constructor, or call `Connection->setSignalDispatch(false)`.  Also, make also have to pass `'socketImpl' => '\amqphp\StreamSocket'` to the Connection constructor, I'm not sure that Windows has the sockets extension.

Let me know if there are any other issues, I don't have a copy of Windows to test on so I'm keen to make sure Amqphp works well there too.

Thanks,
--Robin

**Comment by BraveSirRobin** [comment]
Please re-open this issue is you're still having problem on Windows.
