### ISSUE TITLE
build error with php >= 5.3.9

### ISSUE THREAD

**Issue by hooblei** [BraveSirRobin/amqphp#6]
The phing build with latest php (5.3.9) is flawed and "generateAmqpBindings" doesn't break on these xslt processor errors.
I had to change the xsl.security_prefs setting to allow directory creation and file writes (php default is to disallow all)

```
[xsl]
; Write operations from within XSLT are disabled by default.
; XSL_SECPREF_CREATE_DIRECTORY | XSL_SECPREF_WRITE_NETWORK | XSL_SECPREF_WRITE_FILE = 44
; Set it to 0 to allow all operations
;xsl.security_prefs = 44
```

See php bug https://bugs.php.net/bug.php?id=54446  and 5.3.9 change log entry http://de.php.net/ChangeLog-5.php

**Comment by BraveSirRobin** [comment]
I think a comment ([2011-10-11 05:09 UTC] chregu@php.net) on the linked PHP bug report provides the most likely soluion:

> It's now als in the PHP 5.3.x branch (will be in 5.3.9). We couldn't use the same approach as in PHP 5.4 due to ABI compatibility problems. We had to introduce an ini option. Here's a code example, which works in 5.3 (actually anything >= 5.0) and 5.4 for writing from within XSLT. 
> 
> ---
> 
> $xsl = new XSLTProcessor();
> 
> //if you want to write from within the XSLT
> if (version_compare(PHP_VERSION,'5.4',"<")) {
>     $oldval = ini_set("xsl.security_prefs",XSL_SECPREFS_NONE);
> } else {
>     $oldval = $xsl->setSecurityPreferences(XSL_SECPREFS_NONE);
> }
> 
> $xsl->transformToXml(...);
> 
> //go back to the old setting. Better safe than sorry
> if (version_compare(PHP_VERSION,'5.4',"<")) {
>     ini_set("xsl.security_prefs",$oldval);
> } else {
>     $xsl->setSecurityPreferences($oldval);
>     //or just do
>     // $xsl = null;
>     // to get away of this object
> }

Interestingly, the bug report is for the use of Saxon extensions, whereas Amqphp uses exslt, I guess they're treated the same way.

--Robin

**Comment by BraveSirRobin** [comment]
Hi Markus,

As discussed above, I've applied that fix in [this commit](https://github.com/BraveSirRobin/amqphp/commit/2b12b571010bc16e4d9e36802da43e688f63e1e3).  Please would you download and test this version, (I don't have a copy of PHP 5.3.9, but I have tested this on 5.3.6) and let me know if this fixes the issue.

Thanks,
--Robin

**Comment by hooblei** [comment]
Works - Thank you

Markus
