### ISSUE TITLE
Problem with multibyte encoding and mbstring.func_overload setting

### ISSUE THREAD

**Issue by NarcisDavins** [BraveSirRobin/amqphp#8]
Under some PHP mbstring settings the library doesn't work.

To reproduce it you can for example set these settings

> mbstring.internal_encoding => UTF-8
> mbstring.func_overload => 2

This is because AMQP is a binary protocol and these settings override strlen to act as mb_strlen with the given default encoding.

Do you think this problem could be solved inside the library?

Thank you

**Comment by BraveSirRobin** [comment]
Hi Narcis,

You're right about the cause of this issue, Amqphp requires the standard 8-bit string functions to work at all.  I'm not sure what could be done about this, my best guss would be to add in code to detect the mbstring.func_overload setting and tweak it at run time, if required.  I'll look in to this at the weekend and get back to you.

Thanks,
--Robin

**Comment by BraveSirRobin** [comment]
Hi Narcis,

Had a quick look, and I'm afraid I don't think it's possible to support the mbstring overload feature in Amqphp.  The only possibility you might try is to set a per-directory exception for the directory holding the Amqphp source code, as per the [comment on this page](http://php.net/manual/en/mbstring.overload.php), however a note on the same page seems to suggest this isn't a good idea.

Thanks,
--Robin
