### ISSUE TITLE
Bug when connecting to multiple vhosts on the same server using persistent connection

### ISSUE THREAD

**Issue by tcz** [BraveSirRobin/amqphp#9]
Hi,

We have found the following error when implementing support for you library.

```
Uncaught exception 'Exception' with message 'Failed to reload amqp connection cache during wakeup' in /mnt/user/libs/external/amqphp/src/amqphp/persistent/PConnection.php:318
Stack trace:
#0 /mnt/user/libs/external/amqphp/src/amqphp/persistent/PConnection.php(131): amqphp\persistent\PConnection->wakeup()
#1 /mnt/user/web/engine/MQ.class.php(241): amqphp\persistent\PConnection->connect()
```
### How to reproduce?
- Use persistent connection when connecting to the message queue broker

```
new \amqphp\persistent\PConnection( array(
    'socketParams' => array(
        'url' => 'tcp://' . $connection['host'] . ':' . $connection['port'],
    ),
    'username' => $connection['user'],
    'userpass' => $connection['password'],
    'vhost' => $connection['vhost'],
) );

self::$connection_pool[$key]->pHelperImpl = '\\amqphp\\persistent\\APCPersistenceHelper';
self::$connection_pool[$key]->connect();
```
- Connect to vhost1 on server1
- After the connection is set up for vhost1, connect to vhost2 on server1 (the same server)
### The cause

We have seen that the problem is caused by different caching patterns when persisting inter-request data:
- when creating persistent sockets (with stream_socket_client using STREAM_CLIENT_PERSISTENT flag) the OS persists the connection per url (protocol+hostname+port)
- when persisting connection info for sockets (channels, other amqp-related connection info) the library per url (protocol+hostname+port) AND vhost

When connecting to the 2ns vhost, the library first creates the socket, which has the same URL so it will be reused. This means that its internal pointer (`ftell`) is bigger than 0, so the library supposes that it's a reused connection (correct) and tries to load the data for it. The problem is that the cache key for the connection data is different (the vhost has changed), so it can't find it.

We are happy to help in fixing this by creating a pull request, I just wanted to consult about solutions to see if there is anything you prefer.

I was thinking to change to cache key (`getCK`) of the socket excluding the vhost. This, however, causes problems in other parts of the library (`Stream socket connection created a new wrapper object for an existing persistent connection on URL ...`). Alternatively we can generate the cache key for the persistence helper outside the socket class, or inside with a new method.

What do you think?

**Comment by BraveSirRobin** [comment]
Hi Zoltan,

I'm not sure there is a solution to this issue, the problem is that PHP does persistent connections based only on the "URL", therefore it sees 2 connections to different VHosts on the same broker as a single connecion.   The target Vhost is selected during the connection intiialisation routine, therefore it isn't part of the URL.  The only possible solution I can see is to implement a [custom URL scheme](http://php.net/manual/en/function.stream-wrapper-register.php) for amqp that includes the vhost as part of the URL, but I'm not sure if PHP would play nice with this.

If you're able to submit a patch which resolves this issue then I'll happily take a look, let me now how you get on.  It might be worth asking the question on the PHP mailing list to see if persistent connections can be made to work this way.

Let me know if you're unable to get this going and  I'll take a look at the weekend to see if this can be solved.

Thanks,
--Robin

**Comment by tcz** [comment]
Hi Robin,

Thanks for the prompt answer! I don't see any problem with two different AMQP connections using the same socket, do you?
So at the end the easy solution is let the library reuse the socket and simply change the key generation of the persistence helper.

I will need to test this though. I will look into it tomorrow.

**Comment by BraveSirRobin** [comment]
You can't have more than one AMQP connection for each socket I'm afraid (although amqp is a multiplexed protocol - that's what the channels are for).  If you're using non-persistent connections then you can open more than one socket, but for persistent ones you get the first one back again the second time round - this is the reason for wanting to use a custom URL scheme, as you might be able to selectively bypass the reuse for different vhosts.  For example:

amqp://192.168.1.55/vhost1

would be different to

amqp://192.168.1.55/vhost2

I'm not sure if this is possible, and the only _potential_ solution I can think of (using a custom stream wrapper), would probably be quite invasive and heavyweight., and might not even be possible.  This is why I suggested talking to the PHP list.

--Robin

**Comment by tcz** [comment]
Problem solved.

If you construct the URL like this:

```
'tcp://' . $connection['host'] . ':' . $connection['port'] . '/' . $connection['vhost']
```

... ti will create a distinct persistent connection.per vhost. The part after the port gets ignored. This seems to be a feature of `stream_socket_client`.

I don't even need to touch the library, I can change the URL to which I'm connecting and that's it.
Maybe it would be worth putting this tot eh documentation (and update obsolete documentation of the persistent connections anyway).

Thank you very much!

**Comment by BraveSirRobin** [comment]
Good stuff - thanks for your help!  I'll update the WIKI at the weekend, this is a nice feature.  It's probably worth updating the library so that it always uses the URL scheme you suggest, all the data is there.

--Robin
